services:
  db:
    image: mysql:8.0
    container_name: restify-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend-net

#  app:
#    build: .
#    container_name: restify-app
#    depends_on:
#      - db
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    environment:
#      - JWT_SECRET=${JWT_SECRET}
#      - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
#      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
#      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
#    networks:
#      - backend-net

volumes:
  db_data:

networks:
  backend-net: